In [1]:
import xml.etree.ElementTree as ET

import numpy as np
import cv2
import matplotlib.pyplot as plt
import ast

In [2]:
tree = ET.parse('annotations.xml')
root = tree.getroot()

In [3]:
def parse_line(line):
    individ = line.split(';')
    xy = []
    for each in individ:
        xy.append(np.array(each.split(','), dtype=np.float32))
        # point = []
        # for y in each.split(','):
        #     point.append(np.float64(y))
        # xy.append(np.array(point))

    return np.array(xy)

In [4]:
f1_label = []
f2_label = []
f3_label = []
f4_label = []

for child in root.iter('polyline'):
    child_points = parse_line(child.attrib['points']) # this is a string
    print(child_points)
    if(child.attrib['label'] == 'f1'):
        f1_label.append(child_points)
        #print("f1")
    elif(child.attrib['label'] == 'f2'):
        f2_label.append(child_points)
        #print("f2")
    elif(child.attrib['label'] == 'f3'):
        f3_label.append(child_points)
        #print("f3")
    elif(child.attrib['label'] == 'f4'):
        f4_label.append(child_points)
        #print("f4")

[[328.91 122.67]
 [320.8  124.95]
 [319.53 133.32]
 [320.8  139.65]
 [328.15 142.7 ]
 [336.01 139.65]
 [336.01 127.49]
 [329.17 123.18]]
[[665.02 197.34]
 [671.59 201.31]
 [672.45 207.53]
 [666.75 214.96]
 [669.17 220.66]
 [671.59 225.5 ]
 [677.46 226.71]
 [686.62 227.58]
 [690.25 223.43]
 [696.12 223.26]
 [701.31 227.75]
 [707.35 228.44]
 [712.88 230.51]
 [714.61 247.1 ]
 [705.63 244.86]
 [699.58 245.37]
 [699.41 250.9 ]
 [691.11 253.84]
 [685.06 249.69]
 [676.42 250.04]
 [668.65 250.9 ]
 [668.13 256.43]
 [656.03 258.33]
 [655.34 239.5 ]
 [652.23 226.71]
 [651.54 218.59]
 [642.21 217.9 ]
 [632.01 217.55]
 [628.39 217.55]
 [629.08 208.74]
 [629.77 200.27]
 [638.23 197.51]
 [648.43 196.64]
 [658.28 196.64]
 [664.33 196.64]]
[[248.42 876.21]
 [250.83 864.81]
 [238.74 861.7 ]
 [225.26 864.46]
 [209.71 862.56]
 [203.66 866.71]
 [193.81 873.45]
 [176.7  871.9 ]
 [163.74 871.03]
 [167.89 861.87]
 [156.49 864.29]
 [157.18 879.15]
 [153.38 882.09]
 [143.87 880.54]
 [139.21 875.18]
 [132.47 875

[[811.41 791.19]
 [816.6  793.06]
 [827.79 794.1 ]
 [838.58 791.82]
 [845.83 795.34]
 [845.   805.09]
 [843.55 813.8 ]
 [841.06 819.6 ]
 [821.16 818.15]
 [814.94 818.57]
 [819.71 811.52]
 [819.91 805.29]
 [813.28 803.43]
 [808.51 799.9 ]
 [811.62 790.36]]
[[785.39 835.4 ]
 [772.6  839.72]
 [769.15 848.19]
 [767.42 868.23]
 [768.11 882.75]
 [770.36 890.87]
 [780.9  894.84]
 [783.14 901.75]
 [781.94 911.78]
 [792.65 913.16]
 [796.62 915.92]
 [794.55 922.84]
 [804.23 923.87]
 [807.51 915.23]
 [806.65 903.48]
 [809.24 897.95]
 [819.43 897.43]
 [821.51 904.87]
 [822.54 911.95]
 [827.55 917.31]
 [838.79 919.55]
 [850.54 918.17]
 [849.15 906.07]
 [847.08 901.06]
 [836.19 899.16]
 [829.46 898.82]
 [826.52 895.19]
 [827.9  890.7 ]
 [835.85 886.89]
 [843.97 885.86]
 [846.22 854.06]
 [845.01 843.18]
 [839.82 835.4 ]
 [822.72 833.67]
 [819.09 839.03]
 [808.37 839.03]
 [799.91 832.63]
 [792.48 832.63]
 [799.56 838.68]
 [799.39 844.56]
 [788.16 846.8 ]
 [786.26 842.83]
 [788.85 833.84]
 [785.56 835.

 [637.   329.45]]
[[638.94 353.69]
 [648.31 352.08]
 [654.77 354.02]
 [657.68 360.8 ]
 [654.13 366.3 ]
 [642.17 365.65]
 [636.35 361.45]
 [638.61 355.31]]
[[669.   383.11]
 [678.05 381.17]
 [690.   385.05]
 [687.1  390.54]
 [675.78 392.8 ]
 [667.7  384.4 ]]
[[672.23 402.18]
 [685.16 401.21]
 [692.59 402.18]
 [692.59 409.61]
 [686.77 412.52]
 [675.78 415.1 ]
 [670.61 409.93]
 [671.58 400.88]]
[[609.2  416.72]
 [601.12 419.95]
 [602.09 430.62]
 [604.67 436.11]
 [611.79 435.14]
 [613.72 425.77]
 [614.69 421.25]
 [610.49 417.69]]
[[644.75 411.87]
 [638.94 417.37]
 [639.26 426.09]
 [640.55 434.82]
 [643.46 439.02]
 [650.57 438.7 ]
 [652.51 430.62]
 [652.51 421.25]
 [652.51 416.07]
 [646.05 412.2 ]]
[[681.92 321.37]
 [675.46 327.84]
 [677.4  337.85]
 [684.51 342.7 ]
 [688.07 334.3 ]
 [688.71 323.63]
 [681.28 321.37]]
[[678.69 273.53]
 [671.9  278.06]
 [671.9  283.55]
 [679.66 286.46]
 [688.39 287.11]
 [692.91 282.58]
 [692.27 277.09]
 [683.86 275.15]
 [676.75 273.53]]
[[677.72 251.23]
 [668.

In [9]:
f1_label = np.array(f1_label, dtype=object)
f2_label = np.array(f2_label)
f3_label = np.array(f3_label)
f4_label = np.array(f4_label)

#img = cv2.imread('Snap_Speed3_0_0.jpg')

#points = np.array([[160, 130], [350, 130], [250, 300]])

#cv2.fillPoly(img, np.int32([f1_label]), color=(255, 0, 0))

In [ ]:
img = cv2.imread('Snap_Speed3_0_0.jpg')

#points = np.array([[160, 130], [350, 130], [250, 300]])

cv2.fillPoly(img, np.int32([f1_label]), color=(255, 0, 0))

# cv2.fillPoly(img, np.int32([f2_label]), color=(255, 255, 0))

# cv2.fillPoly(img, np.int32([f3_label]), color=(0, 255, 0))

# cv2.fillPoly(img, np.int32([f4_label]), color=(255, 0, 255))
  
# Displaying the image
#cv2.imshow("filled polygon", img)